# Load zfunc
fpath=( ~/.zfunc "${fpath[@]}" )

# Configuration functions - run then unset
autoload -Uz config_zhist
autoload -Uz history_search_keybindings
autoload -Uz bootstrap_zinit

config_zhist
history_search_keybindings
bootstrap_zinit

unset -f config_zhist
unset -f history_search_keybindings
unset -f bootstrap_zinit

# Utility functions
autoload -Uz startup_check

# Load aliases
. ~/.zaliases

# Set path
export PATH="$PATH:/usr/local/bin"

# Local configuration
if [[ -f ~/.zshrc_local ]]; then
    . ~/.zshrc_local
fi
